In [2]:
import vgg16
%matplotlib inline
import utils; reload(utils)
from utils import *
from __future__ import division, print_function
from keras.layers import TimeDistributed, Activation
from numpy.random import choice

In [6]:
path = get_file('nietzsche.txt', origin="https://s3.amazonaws.com/text-datasets/nietzsche.txt")
text = open(path).read()#.lower()

In [7]:
print(len(text))
print(text[:100])

600901
PREFACE


SUPPOSING that Truth is a woman--what then? Is there not ground
for suspecting that all ph


In [8]:
!tail -n25 {path}

are thinkers who believe in the saints.


144

It stands to reason that this sketch of the saint, made upon the model
of the whole species, can be confronted with many opposing sketches that
would create a more agreeable impression. There are certain exceptions
among the species who distinguish themselves either by especial
gentleness or especial humanity, and perhaps by the strength of their
own personality. Others are in the highest degree fascinating because
certain of their delusions shed a particular glow over their whole
being, as is the case with the founder of christianity who took himself
for the only begotten son of God and hence felt himself sinless; so that
through his imagination--that should not be too harshly judged since the
whole of antiquity swarmed with sons of god--he attained the same goal,
the sense of complete sinlessness, complete irresponsibility, that can
now be attained by every individual through science.--In the same manner
I have viewed the saints of India

In [9]:
chars = sorted(list(set(text)))
chars.insert(0, '\0') # Make the index starting from 1
print(chars)
print(len(chars))
''.join(chars)

['\x00', '\n', ' ', '!', '"', "'", '(', ')', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '=', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\x86', '\xa4', '\xa6', '\xa9', '\xab', '\xc3']
86


'\x00\n !"\'(),-.0123456789:;=?ABCDEFGHIJKLMNOPQRSTUVWXYZ[]_abcdefghijklmnopqrstuvwxyz\x86\xa4\xa6\xa9\xab\xc3'

In [10]:
char_to_index = {c:i for i, c in enumerate(chars)}
index_to_char = {i:c for i, c in enumerate(chars)}

In [11]:
indexes = [char_to_index[c] for c in text]

In [12]:
''.join([index_to_char[i] for i in indexes[:50]])

'PREFACE\n\n\nSUPPOSING that Truth is a woman--what th'

In [9]:
max_len = 40
sentences = []
next_chars = []
for i in range(len(indexes)- max_len):
    sentences.append(indexes[i:i+max_len])
    next_chars.append(indexes[i+1:i+max_len+1])

In [10]:
print(len(sentences))
print(len(next_chars))
#print(text[:50])
print("%s\n%s"%(sentences[-1], next_chars[-1]))

600861
600861
[41, 2, 50, 42, 45, 39, 31, 2, 28, 46, 2, 47, 35, 32, 2, 36, 41, 31, 36, 30, 28, 47, 36, 42, 41, 46, 2, 42, 33, 2, 46, 36, 41, 33, 48, 39, 41, 32, 46, 46]
[2, 50, 42, 45, 39, 31, 2, 28, 46, 2, 47, 35, 32, 2, 36, 41, 31, 36, 30, 28, 47, 36, 42, 41, 46, 2, 42, 33, 2, 46, 36, 41, 33, 48, 39, 41, 32, 46, 46, 10]


In [11]:
#[np.array(s) for s in sentences]
#m = np.concatenate([np.array([s for s in ss]) for ss in sentences])
sentences1 = np.row_stack([[s for s in ss] for ss in sentences])
next_chars1 = np.row_stack([[s for s in ss] for ss in next_chars])
print(sentences1.shape)
print(next_chars1.shape)

(600861, 40)
(600861, 40)


In [12]:
sentences = np.concatenate([[np.array(o)] for o in sentences[:-2]])
next_chars = np.concatenate([[np.array(o)] for o in next_chars[:-2]])

In [13]:
print(sentences.shape)
print(next_chars.shape)

(600859, 40)
(600859, 40)


In [14]:
np.array(sentences[0])

array([43, 45, 32, 33, 28, 30, 32,  1,  1,  1, 46, 48, 43, 43, 42, 46, 36, 41, 34,  2, 47, 35, 28,
       47,  2, 47, 45, 48, 47, 35,  2, 36, 46,  2, 28,  2, 50, 42, 40, 28])

In [16]:
print(next_chars.shape)

(600859, 40)


In [195]:
sentences1[0]

array(['p', 'r', 'e', 'f', 'a', 'c', 'e', '\n', '\n', '\n', 's', 'u', 'p', 'p', 'o', 's', 'i', 'n',
       'g', ' ', 't', 'h', 'a', 't', ' ', 't', 'r', 'u', 't', 'h', ' ', 'i', 's', ' ', 'a', ' ',
       'w', 'o', 'm', 'a'],
      dtype='|S1')

In [52]:
n_fac = 24
vocab_size = len(chars)
print(vocab_size)

86


In [23]:
def print_example():
    seed_string="ethics is a basic foundation of all that"
    for i in range(320):
        x=np.array([char_to_index[c] for c in seed_string[-40:]])[np.newaxis,:]
        preds = model.predict(x, verbose=0)[0][-1]
        preds = preds/np.sum(preds)
        next_char = choice(chars, p=preds)
        seed_string = seed_string + next_char
    print(seed_string)

In [19]:
model=Sequential([
        Embedding(vocab_size, n_fac, input_length=max_len),
        LSTM(512, input_dim=n_fac,return_sequences=True, dropout_U=0.2, dropout_W=0.2,
             consume_less='gpu'),
        Dropout(0.2),
        LSTM(512, return_sequences=True, dropout_U=0.2, dropout_W=0.2,
             consume_less='gpu'),
        Dropout(0.2),
        TimeDistributed(Dense(vocab_size)),
        Activation('softmax')
    ])

/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:4: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.
/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:4: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(512, recurrent_dropout=0.2, implementation=2, dropout=0.2, input_shape=(None, 24), return_sequences=True)`
/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:7: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(512, recurrent_dropout=0.2, implementation=2, dropout=0.2, return_sequences=True)`


In [20]:
model.compile(loss='sparse_categorical_crossentropy', optimizer=Adam())

In [21]:
model.fit(sentences1, np.expand_dims(next_chars1,-1), batch_size=64, nb_epoch=1)

/home/ubuntu/anaconda2/lib/python2.7/site-packages/keras/models.py:939: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/1
600861/600861 [==============================] - 2618s 4ms/step - loss: 1.4950


In [24]:
print_example()

ethics is a basic foundation of all that is seldom fundamental tendency than complex to the free soul, in the metaphysicians, and
here and should aver to exist and as. finally, granting to
which i had not shall be the most delicate and
melanchology of will.--"inspires his "one widen" feels him (are something highly
believed in everything problem of man. a
wi


# 3-Char Model

In [37]:
cs = 3
c1_dat = [indexes[i] for i in range(0, len(indexes)-cs-1, cs)]
c2_dat = [indexes[i+1] for i in range(0, len(indexes)-cs-1, cs)]
c3_dat = [indexes[i+2] for i in range(0, len(indexes)-cs-1, cs)]
c4_dat = [indexes[i+3] for i in range(0, len(indexes)-cs-1, cs)]

In [46]:
#c1_dat = [indexes[i] for i in xrange(0, len(indexes)-1-cs, cs)]
print(len(c1_dat), len(c2_dat), len(c3_dat), len(c4_dat))
print(indexes[:10])
print(c1_dat[0:10])
print(c2_dat[0:10])
print(c3_dat[0:10])
print(c4_dat[0:10])


200299 200299 200299 200299
[40, 42, 29, 30, 25, 27, 29, 1, 1, 1]
[40, 30, 29, 1, 40, 43, 31, 61, 2, 74]
[42, 25, 1, 43, 40, 33, 2, 54, 44, 73]
[29, 27, 1, 45, 39, 38, 73, 73, 71, 61]
[30, 29, 1, 40, 43, 31, 61, 2, 74, 2]


In [47]:
x1 = np.stack(c1_dat)
x2 = np.stack(c2_dat)
x3 = np.stack(c3_dat)
y = np.stack(c4_dat)

In [49]:
print(x1.shape)
print(x2.shape)
print(x3.shape)
print(y.shape)
print(x1[0:5])

(200299,)
(200299,)
(200299,)
(200299,)
[40 30 29  1 40]


In [50]:
x1[:4], x2[:4], x3[:4], y[:4]

(array([40, 30, 29,  1]),
 array([42, 25,  1, 43]),
 array([29, 27,  1, 45]),
 array([30, 29,  1, 40]))

In [51]:
n_fac = 42

In [53]:
def embedding_input(name, n_in, n_out):
    inp = Input(shape=(1,), dtype='int64', name = name)
    emb = Embedding(n_in, n_out, input_length=1)(inp)
    return inp, Flatten()(emb)

In [59]:
c1_in, c1 = embedding_input('c1', vocab_size, n_fac)
c2_in, c2 = embedding_input('c2', vocab_size, n_fac)
c3_in, c3 = embedding_input('c3', vocab_size, n_fac)

In [71]:
n_hidden = 256
dense_in = Dense(n_hidden, activation='relu')
dense_hidden = Dense(n_hidden, activation='tanh')

c1_hidden = dense_in(c1)
hidden_2 = dense_hidden(c1_hidden)
c2_dense = dense_in(c2)
c2_hidden = merge([c2_dense, hidden_2])

/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:8: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
/home/ubuntu/anaconda2/lib/python2.7/site-packages/keras/legacy/layers.py:458: UserWarning: The `Merge` layer is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  name=name)


In [72]:
c3_dense = dense_in(c3)
hidden_3 = dense_hidden(c2_hidden)
c3_hidden=merge([c3_dense, hidden_3])

/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:3: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  app.launch_new_instance()


In [73]:
dense_out = Dense(vocab_size, activation='softmax')
c4_out = dense_out(c3_hidden)


In [74]:
model = Model([c1_in, c2_in, c3_in], c4_out)
model.compile(loss='sparse_categorical_crossentropy', optimizer=Adam())


In [80]:
model.fit([x1, x2, x3], y, batch_size=64, nb_epoch=4)

Epoch 1/4
  2560/200299 [..............................] - ETA: 12s - loss: 2.1501

/home/ubuntu/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  if __name__ == '__main__':


200299/200299 [==============================] - 12s 61us/step - loss: 2.1479
Epoch 2/4
200299/200299 [==============================] - 12s 61us/step - loss: 2.1224
Epoch 3/4
200299/200299 [==============================] - 12s 61us/step - loss: 2.1061
Epoch 4/4
200299/200299 [==============================] - 12s 61us/step - loss: 2.0932


In [88]:
model.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
c3 (InputLayer)                 (None, 1)            0                                            
__________________________________________________________________________________________________
c2 (InputLayer)                 (None, 1)            0                                            
__________________________________________________________________________________________________
c1 (InputLayer)                 (None, 1)            0                                            
__________________________________________________________________________________________________
embedding_6 (Embedding)         (None, 1, 24)        2064        c3[0][0]                         
__________________________________________________________________________________________________
embedding_

In [76]:
def get_next(inp):
    idxs = [char_to_index[c] for c in inp]
    arrs = [np.array(i)[np.newaxis] for i in idxs]
    p = model.predict(arrs)
    i = np.argmax(p)
    return chars[i]

In [81]:
get_next('phi')

'l'

In [82]:
get_next(' th')

'e'

In [87]:
get_next('cha')

'l'